### ISSUE TITLE
Add performance evaluation

### ISSUE THREAD

**Issue by marvey11** [marvey11/codescape-financial-api#17]
For every ISIN/exchange combination return latest share prices in relation to those of a certain base date.

These two share prices can then be used by the caller to calculate relative performance in the interval. 

- ~~Allow support for filtering of ISIN and/or exchange (query parameters)~~
- Add support for grouping the performance by instrument type (if more than one result is returned).

## Tasks
- [x] Add an evaluation controller 
  - [x] Add a GET route "/api/evaluate/performance"
- [x] Add an evaluation service
- Additions to the `QuoteDataService`:
  - [x] Query that returns the latest date and share price in the database as well as the base date and share price on the base date

**Comment by marvey11** [comment]
SQL query that retrieves the max dates and quotes as well as the ref dates and quotes in a single query (with sub-queries):
```sql
-- add the quotes for the reference dates
SELECT rdates.isin AS securityISIN, rdates.sname AS securityName, rdates.ename AS exchangeName, rdates.maxDate as maxDate, rdates.maxQuote as maxQuote, rdates.refDate AS refDate, q.quote AS refQuote
FROM quotes AS q
LEFT JOIN (
    -- calculates the references dates (based on an interval, in this case 1 year; retrieves the latest available date on or before the max date minus interval)
    SELECT mquotes.secID as secID, mquotes.isin as isin, mquotes.sname as sname, mquotes.ename as ename, mquotes.maxDate as maxDate, mquotes.maxQuote as maxQuote, max(q.date) as refDate
    FROM quotes AS q
    LEFT JOIN (
        -- adds the quotes for the maximum dates
        SELECT mdates.secID AS secID, mdates.isin AS isin, mdates.sname AS sname, mdates.ename AS ename, mdates.maxDate AS maxDate, q.quote AS maxQuote
        FROM quotes AS q 
        LEFT JOIN (
            -- the maximum dates for each security
            SELECT s.id AS secID, s.isin AS isin, s.name AS sname, e.name AS ename, MAX(q.date) AS maxDate
            FROM quotes AS q 
            LEFT JOIN securities AS s ON q.securityId = s.id
            LEFT JOIN exchanges AS e ON q.exchangeId = e.id
            GROUP BY s.isin, e.name
        ) AS mdates ON q.securityId = mdates.secID
        WHERE q.date = mdates.maxDate
    ) AS mquotes ON q.securityId = mquotes.secID
    WHERE q.date <= DATE_SUB(mquotes.maxDate, INTERVAL 1 year)
    GROUP BY mquotes.isin, mquotes.ename
) AS rdates ON q.securityId = rdates.secID
WHERE q.date = rdates.refDate;
```

**Comment by marvey11** [comment]
Filtering support will be added in a more general way at a later date (see #23).
