### ISSUE TITLE
Change Security entity to use ISIN as the primary column/key

### ISSUE THREAD

**Issue by marvey11** [marvey11/codescape-financial-api#3]
An ID for the security entity is not strictly necessary as the ISIN by design is already unique.

## Tasks
(Wherever the security's ID is referenced, it should be replaced by the ISIN.)
- Modify `SecuritiesService`
  - [x] `getOne()` is using the ID in one of the overloads (it's probably enough to keep only the one method with the `FindConditions` parameter)
  - [x] `update()` is using the ID to identify the entity to update --> should use the ISIN instead
- Modify `SecurityController`
  - [x] `getOne()` is using the ID as a parameter in the GET request 
  - [x] `update()` is using the ID as a parameter in the PUT request
- Modify the `Security` entity class
  - [x] Remove `id`
  - [x] Add the `@PrimaryColumn()` decorator to `isin`

**Comment by marvey11** [comment]
Also had to change `SecurityController.addOne()` and `SecuritiesService.addOne()` since POSTing now apparently is not complaining about duplicate entries even if the same ISIN is already in the database.

I therefore added a check that first tries to find out whether an item with the same ISIN already exists in the database. In that case it returns `undefined` which has to caught by the controller.
