### ISSUE TITLE
Add data quality evaluation

### ISSUE THREAD

**Issue by marvey11** [marvey11/codescape-financial-api#30]
This evaluation is supposed to find gaps in the price data stored in the database.

### Tasks
- [ ] Add a new database table for non-trading days and relate them to an exchange -- these are specifies days, other than weekends, for which no price data should be expected at that particular exchange
- [ ] Add a controller route (GET) that triggers the evaluation
- [ ] Add an evaluation service that checks for all days between the oldest and the newest share price stored for a particular ISIN/exchange combination whether any days are missing -- expect no prices on weekends and on the non-trading days
