### ISSUE TITLE
Add support for quote data

### ISSUE THREAD

**Issue by marvey11** [marvey11/codescape-financial-api#6]
For the moment I'll add all the quote data for all the securities to the same table.

Each row will consist of an ID, a reference (foreign key) to the security metadata instance, a reference to the exchange the quote data belongs to, a date and a value.

## Tasks
- Entities
  - [x] Create the `QuoteData` entity
  - [x] Update the `Security` entity with the new relations
  - [x] Update the `SecurityExchange` entity with the new relations
- [x] Create an `AddQuoteDataRequest` DTO for adding multiple data items for a single security/exchange combination (example see below)
- [ ] Implement the `QuoteDataService` class; should contain functionality to:
  - [x] Add multiple data items (date/quote) for a single security/exchange combination; and we need to make sure that for the same security/exchange combination and the same date the quote is actually overwritten (i.e. no error occurs)
  - [ ] Get all quotes for a security/exchange combination; with optional parameters for start and end dates
- [ ] Implement the `QuoteDataController` class
  - [x] Add a POST method for adding the data items
  - [ ] Add a GET method for retrieving the data items
  - (no PUT method required as adding quote values for existing security/exchange/date combinations simply overwrites these entries)

## AddQuoteDataRequest DTO JSON Example
```json
{
  "isin": "US02079K1079",
  "exchangeID": 1,
  "quotes": [
    {
      "date": "2021-02-25",
      "quote": 1669.20
    },
    {
      "date": "2021-02-26",
      "quote": 1687.20
    }
  ]
}
```
